name: Cypress Tests
on: [push]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                containers: [1]

        steps:
            - name: Jibble cypress test
              uses: cypress-io/github-action@v6
              with:
                  wait-on: 'http://localhost:5173'
                  start: npx vite --host
                  record: true
                  parallel: true
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
